repos:
- repo: https://github.com/pre-commit/mirrors-isort
  rev: master
  hooks:
  - id: isort
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.6
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: check-json
  - id: check-yaml
  - id: mixed-line-ending
  - id: end-of-file-fixer
  - id: flake8
    language_version: python2.7
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.6
  hooks:
  - id: forbid-crlf
  - id: remove-crlf
  - id: forbid-tabs
