language: python
dist: xenial
sudo: false
notifications:
  email: false
branches:
  only:
    - master
cache:
  pip: true
python:
  - "2.7"
  - "3.6"
install:
  - pip install -U pip==19.0.3
  - pip install -e .
  - pip install coverage
script:
  - set -e
  - coverage run --source=cronman/ setup.py test
  - coverage report
